name: Terraform Plan

on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.15.4
  TF_WORKING_DIR: terraform/environments/dev

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    concurrency:
      group: terraform-dev
      cancel-in-progress: false

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan